### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by enguerran** [MobileChromeApps/cordova-plugin-service-worker#16]
Hi,

What do you think about an Android version for this plugin? I am a very beginner on cordova plugin, and I don't even know if it is feasible.

**Comment by gustavohenke** [comment]
I want this too, mainly because the `file` protocol doesn't allow me to register the worker.

If someone comes to have an answer for this, please: http://stackoverflow.com/questions/36001320/using-serviceworker-in-cordova

**Comment by lcustodio** [comment]
In theory there a way to [loose the restriction](https://www.w3.org/TR/service-workers/#security-considerations) for development. As serving from `file://` in cordova is not a security constrain, the option could be considered.

**Comment by enguerran** [comment]
No sign of life, I close this issue.

**Comment by Textras** [comment]
@lcustodio have you ever succeeded with Android workaround? Perhaps iFrame or some other hacky solution?

**Comment by lcustodio** [comment]
Hi @Textras, it's a long time since I worked on this project. As far as I remember it didn't work, the final solution was based on a service (not related to web worker) that kept the state coherent between device and server.
